mytestkey=This value is from LOCAL properties file

paypal.client.id=AcalQXoPrTfiXKPmW_ypberGgI2gumYt_8qLJ4MHZ7aIAlY9tZSLCaerPOTS0Q5YW_bQDyJf0GF9kh5_
paypal.client.secret=EAn3EeVIHmpJWmj2YeHYU9r1lCHNxr3Q_poXxSc7_x-HL50SDXGGsolJNoK3dLB04fOG_aktNXuAxyO0

paypal.oauth.url=https://api-m.sandbox.paypal.com/v1/oauth2/token
paypal.create.order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders
paypal.capture.order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders/{orderId}/capture

# ========= Eureka Client Configuration =========
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

# ========= Redis Configuration =========
spring.data.redis.host=localhost
spring.data.redis.port=6379