mytestkey=This value is from DOCKER properties file

spring.datasource.url=jdbc:mysql://mysql:3306/payments
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

paypalprovider.createorder.url=http://paypal-provider/orders
paypalprovider.captureorder.url=http://paypal-provider/orders/{provider-reference}/capture
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# ========= Eureka Client Configuration =========
eureka.client.service-url.defaultZone=http://eureka:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

# ========= Redis Configuration =========
spring.data.redis.host=redis
spring.data.redis.port=6379
